
// Generated by Cadence Genus(TM) Synthesis Solution 22.17-s071_1
// Generated on: Jul  9 2026 03:19:56 KST (Jul  8 2026 18:19:56 UTC)

// Verification Directory fv/counter_100 

module counter_100(clk, rst_n, i_btn, o_cnt);
  input clk, rst_n, i_btn;
  output [5:0] o_cnt;
  wire clk, rst_n, i_btn;
  wire [5:0] o_cnt;
  wire [1:0] state;
  wire [25:0] clk_cnt;
  wire inc_add_69_25_n_0, inc_add_69_25_n_2, inc_add_69_25_n_4,
       inc_add_69_25_n_6, inc_add_69_25_n_9, inc_add_69_25_n_10,
       inc_add_69_25_n_12, inc_add_69_25_n_14;
  wire inc_add_69_25_n_16, inc_add_69_25_n_18, inc_add_69_25_n_21,
       inc_add_69_25_n_22, inc_add_69_25_n_25, inc_add_69_25_n_26,
       inc_add_69_25_n_28, inc_add_69_25_n_30;
  wire inc_add_69_25_n_32, inc_add_69_25_n_34, inc_add_69_25_n_36,
       inc_add_69_25_n_38, inc_add_69_25_n_40, inc_add_69_25_n_42,
       inc_add_69_25_n_44, inc_add_69_25_n_46;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_82, n_83, n_84, n_85, n_86;
  SDFFRHQX1 \clk_cnt_reg[0] (.RN (rst_n), .CK (clk), .D (n_20), .SI
       (state[1]), .SE (clk_cnt[0]), .Q (clk_cnt[0]));
  DFFRHQX1 \clk_cnt_reg[1] (.RN (rst_n), .CK (clk), .D (n_44), .Q
       (clk_cnt[1]));
  DFFRHQX1 \clk_cnt_reg[2] (.RN (rst_n), .CK (clk), .D (n_31), .Q
       (clk_cnt[2]));
  DFFRHQX1 \clk_cnt_reg[3] (.RN (rst_n), .CK (clk), .D (n_30), .Q
       (clk_cnt[3]));
  DFFRHQX1 \clk_cnt_reg[4] (.RN (rst_n), .CK (clk), .D (n_29), .Q
       (clk_cnt[4]));
  DFFRHQX1 \clk_cnt_reg[5] (.RN (rst_n), .CK (clk), .D (n_28), .Q
       (clk_cnt[5]));
  DFFRHQX1 \clk_cnt_reg[6] (.RN (rst_n), .CK (clk), .D (n_27), .Q
       (clk_cnt[6]));
  DFFRHQX1 \clk_cnt_reg[7] (.RN (rst_n), .CK (clk), .D (n_26), .Q
       (clk_cnt[7]));
  DFFRHQX1 \clk_cnt_reg[8] (.RN (rst_n), .CK (clk), .D (n_25), .Q
       (clk_cnt[8]));
  DFFRHQX1 \clk_cnt_reg[9] (.RN (rst_n), .CK (clk), .D (n_37), .Q
       (clk_cnt[9]));
  DFFRHQX1 \clk_cnt_reg[10] (.RN (rst_n), .CK (clk), .D (n_47), .Q
       (clk_cnt[10]));
  DFFRHQX1 \clk_cnt_reg[11] (.RN (rst_n), .CK (clk), .D (n_46), .Q
       (clk_cnt[11]));
  DFFRHQX1 \clk_cnt_reg[12] (.RN (rst_n), .CK (clk), .D (n_45), .Q
       (clk_cnt[12]));
  DFFRHQX1 \clk_cnt_reg[13] (.RN (rst_n), .CK (clk), .D (n_43), .Q
       (clk_cnt[13]));
  DFFRHQX1 \clk_cnt_reg[14] (.RN (rst_n), .CK (clk), .D (n_42), .Q
       (clk_cnt[14]));
  DFFRHQX1 \clk_cnt_reg[15] (.RN (rst_n), .CK (clk), .D (n_41), .Q
       (clk_cnt[15]));
  DFFRHQX1 \clk_cnt_reg[16] (.RN (rst_n), .CK (clk), .D (n_40), .Q
       (clk_cnt[16]));
  DFFRHQX1 \clk_cnt_reg[17] (.RN (rst_n), .CK (clk), .D (n_39), .Q
       (clk_cnt[17]));
  DFFRHQX1 \clk_cnt_reg[18] (.RN (rst_n), .CK (clk), .D (n_38), .Q
       (clk_cnt[18]));
  DFFRHQX1 \clk_cnt_reg[19] (.RN (rst_n), .CK (clk), .D (n_48), .Q
       (clk_cnt[19]));
  DFFRHQX1 \clk_cnt_reg[20] (.RN (rst_n), .CK (clk), .D (n_24), .Q
       (clk_cnt[20]));
  DFFRHQX1 \clk_cnt_reg[21] (.RN (rst_n), .CK (clk), .D (n_36), .Q
       (clk_cnt[21]));
  DFFRHQX1 \clk_cnt_reg[22] (.RN (rst_n), .CK (clk), .D (n_35), .Q
       (clk_cnt[22]));
  DFFRHQX1 \clk_cnt_reg[23] (.RN (rst_n), .CK (clk), .D (n_34), .Q
       (clk_cnt[23]));
  DFFRHQX1 \clk_cnt_reg[24] (.RN (rst_n), .CK (clk), .D (n_33), .Q
       (clk_cnt[24]));
  DFFRHQX1 \clk_cnt_reg[25] (.RN (rst_n), .CK (clk), .D (n_32), .Q
       (clk_cnt[25]));
  DFFRHQX1 \o_cnt_reg[0] (.RN (rst_n), .CK (clk), .D (n_50), .Q
       (o_cnt[0]));
  SDFFRHQX1 \o_cnt_reg[1] (.RN (rst_n), .CK (clk), .D (n_23), .SI
       (n_49), .SE (o_cnt[1]), .Q (o_cnt[1]));
  DFFRHQX1 \o_cnt_reg[5] (.RN (rst_n), .CK (clk), .D (n_61), .Q
       (o_cnt[5]));
  SDFFRHQX1 \state_reg[0] (.RN (rst_n), .CK (clk), .D (n_8), .SI (n_1),
       .SE (i_btn), .Q (state[0]));
  OAI2BB1X1 g3600__2398(.A0N (o_cnt[5]), .A1N (n_59), .B0 (n_58), .Y
       (n_61));
  OAI32X1 g3602__5107(.A0 (o_cnt[4]), .A1 (n_2), .A2 (n_51), .B0 (n_6),
       .B1 (n_56), .Y (n_60));
  OAI2BB1X1 g3603__6260(.A0N (state[0]), .A1N (n_6), .B0 (n_56), .Y
       (n_59));
  OR4X1 g3605__4319(.A (o_cnt[5]), .B (n_2), .C (n_6), .D (n_51), .Y
       (n_58));
  OAI22X1 g3606__8428(.A0 (n_2), .A1 (n_54), .B0 (o_cnt[3]), .B1
       (n_51), .Y (n_57));
  OAI32X1 g3608__5526(.A0 (o_cnt[2]), .A1 (n_3), .A2 (n_22), .B0 (n_4),
       .B1 (n_52), .Y (n_55));
  AOI21X1 g3609__6783(.A0 (state[0]), .A1 (n_2), .B0 (n_53), .Y (n_56));
  INVX1 g3611(.A (n_53), .Y (n_54));
  OAI2BB1X1 g3612__3680(.A0N (state[0]), .A1N (n_4), .B0 (n_52), .Y
       (n_53));
  OAI31X1 g3627__1617(.A0 (o_cnt[0]), .A1 (n_9), .A2 (n_19), .B0 (n_0),
       .Y (n_50));
  AOI21X1 g3628__2802(.A0 (state[0]), .A1 (n_3), .B0 (n_49), .Y (n_52));
  NAND3X1 g3639__1705(.A (o_cnt[1]), .B (o_cnt[2]), .C (n_23), .Y
       (n_51));
  AO22XL g3643__5122(.A0 (n_80), .A1 (n_20), .B0 (clk_cnt[19]), .B1
       (state[1]), .Y (n_48));
  AO22XL g3644__8246(.A0 (n_71), .A1 (n_20), .B0 (clk_cnt[10]), .B1
       (state[1]), .Y (n_47));
  AO22XL g3645__7098(.A0 (n_72), .A1 (n_20), .B0 (clk_cnt[11]), .B1
       (state[1]), .Y (n_46));
  AO22XL g3646__6131(.A0 (n_73), .A1 (n_20), .B0 (clk_cnt[12]), .B1
       (state[1]), .Y (n_45));
  AO22XL g3647__1881(.A0 (n_62), .A1 (n_20), .B0 (clk_cnt[1]), .B1
       (state[1]), .Y (n_44));
  AO22XL g3648__5115(.A0 (n_74), .A1 (n_20), .B0 (clk_cnt[13]), .B1
       (state[1]), .Y (n_43));
  AO22XL g3649__7482(.A0 (n_75), .A1 (n_20), .B0 (clk_cnt[14]), .B1
       (state[1]), .Y (n_42));
  AO22XL g3650__4733(.A0 (n_76), .A1 (n_20), .B0 (clk_cnt[15]), .B1
       (state[1]), .Y (n_41));
  AO22XL g3651__6161(.A0 (n_77), .A1 (n_20), .B0 (clk_cnt[16]), .B1
       (state[1]), .Y (n_40));
  AO22XL g3652__9315(.A0 (n_78), .A1 (n_20), .B0 (clk_cnt[17]), .B1
       (state[1]), .Y (n_39));
  AO22XL g3653__9945(.A0 (n_79), .A1 (n_20), .B0 (clk_cnt[18]), .B1
       (state[1]), .Y (n_38));
  OAI21X1 g3654__2883(.A0 (o_cnt[0]), .A1 (n_1), .B0 (n_21), .Y (n_49));
  AO22XL g3655__2346(.A0 (n_70), .A1 (n_20), .B0 (clk_cnt[9]), .B1
       (state[1]), .Y (n_37));
  AO22XL g3656__1666(.A0 (n_82), .A1 (n_20), .B0 (clk_cnt[21]), .B1
       (state[1]), .Y (n_36));
  AO22XL g3657__7410(.A0 (n_83), .A1 (n_20), .B0 (clk_cnt[22]), .B1
       (state[1]), .Y (n_35));
  AO22XL g3658__6417(.A0 (n_84), .A1 (n_20), .B0 (clk_cnt[23]), .B1
       (state[1]), .Y (n_34));
  AO22XL g3659__5477(.A0 (n_85), .A1 (n_20), .B0 (clk_cnt[24]), .B1
       (state[1]), .Y (n_33));
  AO22XL g3660__2398(.A0 (n_86), .A1 (n_20), .B0 (clk_cnt[25]), .B1
       (state[1]), .Y (n_32));
  AO22XL g3661__5107(.A0 (n_63), .A1 (n_20), .B0 (clk_cnt[2]), .B1
       (state[1]), .Y (n_31));
  AO22XL g3662__6260(.A0 (n_64), .A1 (n_20), .B0 (clk_cnt[3]), .B1
       (state[1]), .Y (n_30));
  AO22XL g3663__4319(.A0 (n_65), .A1 (n_20), .B0 (clk_cnt[4]), .B1
       (state[1]), .Y (n_29));
  AO22XL g3664__8428(.A0 (n_66), .A1 (n_20), .B0 (clk_cnt[5]), .B1
       (state[1]), .Y (n_28));
  AO22XL g3665__5526(.A0 (n_67), .A1 (n_20), .B0 (clk_cnt[6]), .B1
       (state[1]), .Y (n_27));
  AO22XL g3666__6783(.A0 (n_68), .A1 (n_20), .B0 (clk_cnt[7]), .B1
       (state[1]), .Y (n_26));
  AO22XL g3667__3680(.A0 (n_69), .A1 (n_20), .B0 (clk_cnt[8]), .B1
       (state[1]), .Y (n_25));
  AO22XL g3668__1617(.A0 (n_81), .A1 (n_20), .B0 (clk_cnt[20]), .B1
       (state[1]), .Y (n_24));
  INVX1 g3669(.A (n_23), .Y (n_22));
  NOR3BX1 g3670__2802(.AN (o_cnt[0]), .B (n_9), .C (n_19), .Y (n_23));
  AOI21X1 g3672__1705(.A0 (state[0]), .A1 (n_19), .B0 (state[1]), .Y
       (n_21));
  AND2X1 g3673__5122(.A (n_19), .B (n_8), .Y (n_20));
  OR4X1 g3674__8246(.A (clk_cnt[23]), .B (clk_cnt[24]), .C
       (clk_cnt[25]), .D (n_18), .Y (n_19));
  OR4X1 g3675__7098(.A (clk_cnt[20]), .B (clk_cnt[21]), .C
       (clk_cnt[22]), .D (n_17), .Y (n_18));
  OR4X1 g3676__6131(.A (clk_cnt[17]), .B (clk_cnt[18]), .C
       (clk_cnt[19]), .D (n_16), .Y (n_17));
  OR4X1 g3677__1881(.A (clk_cnt[14]), .B (clk_cnt[15]), .C
       (clk_cnt[16]), .D (n_15), .Y (n_16));
  OR4X1 g3678__5115(.A (clk_cnt[11]), .B (clk_cnt[12]), .C
       (clk_cnt[13]), .D (n_14), .Y (n_15));
  OR4X1 g3679__7482(.A (clk_cnt[8]), .B (clk_cnt[9]), .C (clk_cnt[10]),
       .D (n_13), .Y (n_14));
  OR4X1 g3680__4733(.A (clk_cnt[5]), .B (clk_cnt[6]), .C (clk_cnt[7]),
       .D (n_12), .Y (n_13));
  NAND3BXL g3682__6161(.AN (clk_cnt[4]), .B (clk_cnt[3]), .C (n_10), .Y
       (n_12));
  OAI32X1 g3684__9315(.A0 (i_btn), .A1 (state[0]), .A2 (n_5), .B0
       (n_7), .B1 (n_9), .Y (n_11));
  NOR3BX1 g3685__9945(.AN (clk_cnt[0]), .B (clk_cnt[1]), .C
       (clk_cnt[2]), .Y (n_10));
  INVX1 g3686(.A (n_9), .Y (n_8));
  NAND2X1 g3687__2883(.A (state[0]), .B (n_5), .Y (n_9));
  INVX1 g3688(.A (i_btn), .Y (n_7));
  INVX1 g3692(.A (o_cnt[1]), .Y (n_3));
  INVX1 g3694(.A (state[0]), .Y (n_1));
  NAND2BX1 g2__2346(.AN (n_21), .B (o_cnt[0]), .Y (n_0));
  XNOR2X1 inc_add_69_25_g329__1666(.A (clk_cnt[25]), .B
       (inc_add_69_25_n_46), .Y (n_86));
  OA21X1 inc_add_69_25_g330__7410(.A0 (clk_cnt[24]), .A1
       (inc_add_69_25_n_44), .B0 (inc_add_69_25_n_46), .Y (n_85));
  NAND2X1 inc_add_69_25_g331__6417(.A (clk_cnt[24]), .B
       (inc_add_69_25_n_44), .Y (inc_add_69_25_n_46));
  XNOR2X1 inc_add_69_25_g332__5477(.A (clk_cnt[23]), .B
       (inc_add_69_25_n_42), .Y (n_84));
  NOR2BX1 inc_add_69_25_g333__2398(.AN (clk_cnt[23]), .B
       (inc_add_69_25_n_42), .Y (inc_add_69_25_n_44));
  OA21X1 inc_add_69_25_g334__5107(.A0 (clk_cnt[22]), .A1
       (inc_add_69_25_n_40), .B0 (inc_add_69_25_n_42), .Y (n_83));
  NAND2X1 inc_add_69_25_g335__6260(.A (clk_cnt[22]), .B
       (inc_add_69_25_n_40), .Y (inc_add_69_25_n_42));
  AOI2BB1XL inc_add_69_25_g336__4319(.A0N (clk_cnt[21]), .A1N
       (inc_add_69_25_n_38), .B0 (inc_add_69_25_n_40), .Y (n_82));
  AND2XL inc_add_69_25_g337__8428(.A (clk_cnt[21]), .B
       (inc_add_69_25_n_38), .Y (inc_add_69_25_n_40));
  XNOR2X1 inc_add_69_25_g338__5526(.A (clk_cnt[20]), .B
       (inc_add_69_25_n_36), .Y (n_81));
  NOR2BX1 inc_add_69_25_g339__6783(.AN (clk_cnt[20]), .B
       (inc_add_69_25_n_36), .Y (inc_add_69_25_n_38));
  OA21X1 inc_add_69_25_g340__3680(.A0 (clk_cnt[19]), .A1
       (inc_add_69_25_n_34), .B0 (inc_add_69_25_n_36), .Y (n_80));
  NAND2X1 inc_add_69_25_g341__1617(.A (clk_cnt[19]), .B
       (inc_add_69_25_n_34), .Y (inc_add_69_25_n_36));
  AOI2BB1XL inc_add_69_25_g342__2802(.A0N (clk_cnt[18]), .A1N
       (inc_add_69_25_n_32), .B0 (inc_add_69_25_n_34), .Y (n_79));
  AND2XL inc_add_69_25_g343__1705(.A (clk_cnt[18]), .B
       (inc_add_69_25_n_32), .Y (inc_add_69_25_n_34));
  XNOR2X1 inc_add_69_25_g344__5122(.A (clk_cnt[17]), .B
       (inc_add_69_25_n_30), .Y (n_78));
  NOR2BX1 inc_add_69_25_g345__8246(.AN (clk_cnt[17]), .B
       (inc_add_69_25_n_30), .Y (inc_add_69_25_n_32));
  XNOR2X1 inc_add_69_25_g346__7098(.A (clk_cnt[16]), .B
       (inc_add_69_25_n_28), .Y (n_77));
  NAND2BX1 inc_add_69_25_g347__6131(.AN (inc_add_69_25_n_28), .B
       (clk_cnt[16]), .Y (inc_add_69_25_n_30));
  OA21X1 inc_add_69_25_g348__1881(.A0 (clk_cnt[15]), .A1
       (inc_add_69_25_n_26), .B0 (inc_add_69_25_n_28), .Y (n_76));
  NAND2X1 inc_add_69_25_g349__5115(.A (clk_cnt[15]), .B
       (inc_add_69_25_n_26), .Y (inc_add_69_25_n_28));
  AOI2BB1XL inc_add_69_25_g350__7482(.A0N (clk_cnt[14]), .A1N
       (inc_add_69_25_n_25), .B0 (inc_add_69_25_n_26), .Y (n_75));
  AND2XL inc_add_69_25_g351__4733(.A (clk_cnt[14]), .B
       (inc_add_69_25_n_25), .Y (inc_add_69_25_n_26));
  ADDHX1 inc_add_69_25_g352__6161(.A (clk_cnt[13]), .B
       (inc_add_69_25_n_22), .CO (inc_add_69_25_n_25), .S (n_74));
  AOI2BB1XL inc_add_69_25_g353__9315(.A0N (clk_cnt[12]), .A1N
       (inc_add_69_25_n_21), .B0 (inc_add_69_25_n_22), .Y (n_73));
  AND2XL inc_add_69_25_g354__9945(.A (clk_cnt[12]), .B
       (inc_add_69_25_n_21), .Y (inc_add_69_25_n_22));
  ADDHX1 inc_add_69_25_g355__2883(.A (clk_cnt[11]), .B
       (inc_add_69_25_n_18), .CO (inc_add_69_25_n_21), .S (n_72));
  AOI2BB1XL inc_add_69_25_g356__2346(.A0N (clk_cnt[10]), .A1N
       (inc_add_69_25_n_16), .B0 (inc_add_69_25_n_18), .Y (n_71));
  AND2XL inc_add_69_25_g357__1666(.A (clk_cnt[10]), .B
       (inc_add_69_25_n_16), .Y (inc_add_69_25_n_18));
  AOI2BB1XL inc_add_69_25_g358__7410(.A0N (clk_cnt[9]), .A1N
       (inc_add_69_25_n_14), .B0 (inc_add_69_25_n_16), .Y (n_70));
  AND2XL inc_add_69_25_g359__6417(.A (clk_cnt[9]), .B
       (inc_add_69_25_n_14), .Y (inc_add_69_25_n_16));
  XNOR2X1 inc_add_69_25_g360__5477(.A (clk_cnt[8]), .B
       (inc_add_69_25_n_12), .Y (n_69));
  NOR2BX1 inc_add_69_25_g361__2398(.AN (clk_cnt[8]), .B
       (inc_add_69_25_n_12), .Y (inc_add_69_25_n_14));
  OA21X1 inc_add_69_25_g362__5107(.A0 (clk_cnt[7]), .A1
       (inc_add_69_25_n_10), .B0 (inc_add_69_25_n_12), .Y (n_68));
  NAND2X1 inc_add_69_25_g363__6260(.A (clk_cnt[7]), .B
       (inc_add_69_25_n_10), .Y (inc_add_69_25_n_12));
  AOI2BB1XL inc_add_69_25_g364__4319(.A0N (clk_cnt[6]), .A1N
       (inc_add_69_25_n_9), .B0 (inc_add_69_25_n_10), .Y (n_67));
  AND2XL inc_add_69_25_g365__8428(.A (clk_cnt[6]), .B
       (inc_add_69_25_n_9), .Y (inc_add_69_25_n_10));
  ADDHX1 inc_add_69_25_g366__5526(.A (clk_cnt[5]), .B
       (inc_add_69_25_n_6), .CO (inc_add_69_25_n_9), .S (n_66));
  AOI2BB1XL inc_add_69_25_g367__6783(.A0N (clk_cnt[4]), .A1N
       (inc_add_69_25_n_4), .B0 (inc_add_69_25_n_6), .Y (n_65));
  AND2XL inc_add_69_25_g368__3680(.A (clk_cnt[4]), .B
       (inc_add_69_25_n_4), .Y (inc_add_69_25_n_6));
  AOI2BB1XL inc_add_69_25_g369__1617(.A0N (clk_cnt[3]), .A1N
       (inc_add_69_25_n_2), .B0 (inc_add_69_25_n_4), .Y (n_64));
  AND2XL inc_add_69_25_g370__2802(.A (clk_cnt[3]), .B
       (inc_add_69_25_n_2), .Y (inc_add_69_25_n_4));
  AOI2BB1XL inc_add_69_25_g371__1705(.A0N (clk_cnt[2]), .A1N
       (inc_add_69_25_n_0), .B0 (inc_add_69_25_n_2), .Y (n_63));
  AND2XL inc_add_69_25_g372__5122(.A (clk_cnt[2]), .B
       (inc_add_69_25_n_0), .Y (inc_add_69_25_n_2));
  AOI2BB1XL inc_add_69_25_g373__8246(.A0N (clk_cnt[0]), .A1N
       (clk_cnt[1]), .B0 (inc_add_69_25_n_0), .Y (n_62));
  AND2XL inc_add_69_25_g374__7098(.A (clk_cnt[0]), .B (clk_cnt[1]), .Y
       (inc_add_69_25_n_0));
  DFFRX1 \o_cnt_reg[4] (.RN (rst_n), .CK (clk), .D (n_60), .Q
       (o_cnt[4]), .QN (n_6));
  DFFRX1 \state_reg[1] (.RN (rst_n), .CK (clk), .D (n_11), .Q
       (state[1]), .QN (n_5));
  DFFRX1 \o_cnt_reg[2] (.RN (rst_n), .CK (clk), .D (n_55), .Q
       (o_cnt[2]), .QN (n_4));
  DFFRX1 \o_cnt_reg[3] (.RN (rst_n), .CK (clk), .D (n_57), .Q
       (o_cnt[3]), .QN (n_2));
endmodule

