
// Generated by Cadence Genus(TM) Synthesis Solution 22.17-s071_1
// Generated on: Jul  8 2026 03:07:04 KST (Jul  7 2026 18:07:04 UTC)

// Verification Directory fv/gpio_mux 

module gpio_mux(in_0, in_1, in_2, in_3, sel, out);
  input in_0, in_1, in_2, in_3;
  input [1:0] sel;
  output out;
  wire in_0, in_1, in_2, in_3;
  wire [1:0] sel;
  wire out;
  MX4XL g90__2398(.A (in_0), .B (in_2), .C (in_1), .D (in_3), .S0
       (sel[1]), .S1 (sel[0]), .Y (out));
endmodule

